### ISSUE TITLE
Icons are not displayed in the latest versions of the CICS extension

### ISSUE THREAD

**Issue by zFernand0** [zowe/cics-for-zowe-client#112]
**Describe the bug**

Icons are not displaying for the CICS extension

**Expected and actual results**

|**Before**|**After**|
|-|-|
|![image](https://github.com/zowe/cics-for-zowe-client/assets/37381190/8241e290-ce13-4e1a-b7c5-1a4839c0f7e2)|![image](https://github.com/zowe/cics-for-zowe-client/assets/37381190/68c5fe22-8edc-416e-bdc5-5c1a12046163)|

**Describe your environment**

CICS VSCE: 2.3.4

**Additional context**

Credits to @Joe-Winchester

**Comment by Joe-Winchester** [comment]
Hi @zFernand0 ,  thank you for creating a fix so quickly !    For the .vsix link https://open-vsx.org/extension/Zowe/cics-extension-for-zowe and it's tagged as v3.0 so I can't load it into a v2 Zowe Explorer.  Is there a V2 .vsix file I can use to test (and also demo with as I'm at SHARE this week),  I've found an older build on the old repo and managed to get that working Cheers for the fast turnaround !!

<img width="568" alt="image" src="https://github.com/zowe/cics-for-zowe-client/assets/28100302/0af1b4b5-bf39-40c2-b446-b09c179568ad">

**Comment by adam-wolfe** [comment]
Hi @Joe-Winchester, you should be able to select version 2.3.5 on open-vsx.org. the V2 version is also available here: https://github.com/zowe/cics-for-zowe-client/releases/tag/v5.0.5
