### ISSUE TITLE
Broken link to image on VS Code Marketplace

### ISSUE THREAD

**Issue by FALLAI-Denis** [zowe/cics-for-zowe-client#155]
**Describe the bug**

Links to images are broken on the VS Code Marketplace site.

![image](https://github.com/user-attachments/assets/dbb36789-d08c-4227-8e6a-cb20bb3ec235)

**Expected and actual results**

![image](https://github.com/user-attachments/assets/ac41ef54-07e9-49e4-b83f-c81304d9cc33)

Thanks.

**Comment by zFernand0** [comment]
- Fixed in #156 
  Thanks @adam-wolfe
