### ISSUE TITLE
Have option to create team config file

### ISSUE THREAD

**Issue by JillieBeanSim** [zowe/cics-for-zowe-client#33]
The extension recognizes and uses team config files, but if no team config file is in place and user tries to create profile from CICS view the user is presented with v1 profile creation steps and isn't offered the option to create team config file.

**Comment by zFernand0** [comment]
I'm afraid this didn't seem to make it into the roadmap [during PI planning](https://github.com/zowe/community/blob/master/Project%20Management/PI%20Planning/24PI4%20Planning/PI%20Planning%20Preparation%20by%20Squad/Zowe%20Explorer%20Squad%20-%2024PI4%20Objectives.md), however, this seems like something we need to address as soon as practicable 🙏

**Comment by davenice** [comment]
PR https://github.com/zowe/cics-for-zowe-client/pull/160 means that the `+` icon on the CICS view now redirects to the config file correctly.

Right-clicking on a profile and choosing update pops up the bad dialog.
Choosing delete does nothing.

Chin is working this to completion 👌

**Comment by chinmdas** [comment]
With the fixes going in as part of PR https://github.com/zowe/cics-for-zowe-client/issues/33 , following will be experienced by users upon click of `+` icon:

- `zowe.config.json` is **missing** -> **New Team Config File is created**
- `zowe.config.json` file is **available**, but CICS Profile is **missing** -> **Edit Team Config File**
- `zowe.config.json` file is **available** + CICS Profile is **available**  -> **Edit Team Config File**
