### ISSUE TITLE
Unable to load in Zowe Explorer 2.8

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/cics-for-zowe-client#34]
In Zowe Explorer 2.8 the Zowe Explorer for IBM CICS fails to load, with a busy cursor and no completion.
In an environment where the extension is already loaded no tree data is shown and when trying to add a connection from the list of profiles the following error occurs.
<img width="466" alt="image" src="https://user-images.githubusercontent.com/28100302/236413517-43b18009-26cb-4974-8106-3ce5589cf565.png">

**Comment by zFernand0** [comment]
Related to:
- #33

**Comment by zFernand0** [comment]
This is still an issue with ZE 2.14.1.
The CICS Schema does not get updated on `initForZowe`,
However, this should be resolved with 2.15.0 (kudos to @traeok)
We can close this issue once the PR below is merged
- https://github.com/zowe/vscode-extension-for-zowe/pull/2748

**Comment by zFernand0** [comment]
This issue has been resolved for all extenders that register to Zowe Explorer after its 2.15.0 update
