### ISSUE TITLE
Error running command cics-extension-for-zowe.addSession: command 'cics-extension-for-zowe.addSession' not found. This is likely caused by the extension that contributes cics-extension-for-zowe.addSession.

### ISSUE THREAD

**Issue by jagbr01** [zowe/cics-for-zowe-client#37]
I have installed the extension, I have my profile for CICS created and it doesn't show up and it give me this error when I try to add.

Error running command cics-extension-for-zowe.addSession: command 'cics-extension-for-zowe.addSession' not found. This is likely caused by the extension that contributes cics-extension-for-zowe.addSession.

**Comment by zFernand0** [comment]
This should be resolved on both, V1 and V2.
Apologies for the delay.
