### ISSUE TITLE
Create a test pipeline

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/cics-for-zowe-client#71]

**Comment by zFernand0** [comment]
The only remaining items are:
- [ ] #18
- Setup Integration tests with: [redhat-developer/vscode-extension-tester](https://github.com/redhat-developer/vscode-extension-tester)

**Comment by zFernand0** [comment]
Closing this issue in favor of:
-  #18 

Also, we should follow Zowe Explorer's best practices for adding integration tests to the CICS VSCE
